# train.py

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from torchvision import models
from sklearn.metrics import roc_auc_score, f1_score, confusion_matrix
import torchvision.transforms.functional as TF
from PIL import Image

from losses           import AsymmetricLoss, LabelSmoothingASL
from augmentation     import CXRAugmentation
from stratified_split import build_stratified_splits
from foundation_init  import build_masked_cxr_resnet34, get_layer_groups

logging.basicConfig(
    level  = logging.INFO,
    format = "%(asctime)s %(levelname)-8s %(name)s %(message)s",
)
logger = logging.getLogger(__name__)


# ── Dataset ───────────────────────────────────────────────────────────────────

class MaskedCXRDataset(Dataset):
    """
    Loads pre-computed PSPNet masks from disk (generated by dataset_preparation.py).
    If mask is missing, falls back to all-ones (passthrough) — same as segmenter
    fallback behavior, ensuring training/inference consistency.
    """
    
    def __init__(
        self,
        df:           pd.DataFrame,
        mask_dir:     Path,
        augmentation: CXRAugmentation,
    ):
        self.df           = df.reset_index(drop=True)
        self.mask_dir     = Path(mask_dir)
        self.augmentation = augmentation
    
    def __len__(self) -> int:
        return len(self.df)
    
    def __getitem__(self, idx: int) -> tuple[torch.Tensor, int]:
        row   = self.df.iloc[idx]
        image = Image.open(row["image_path"]).convert("RGB")
        label = int(row["label"])
        
        # Load pre-computed mask
        mask_path = self.mask_dir / (Path(row["image_path"]).stem + ".npy")
        if mask_path.exists():
            mask = np.load(mask_path).astype(np.float32)
        else:
            logger.warning("Mask missing for %s — using passthrough", row["image_path"])
            mask = np.ones((224, 224), dtype=np.float32)
        
        tensor, _ = self.augmentation(image, mask)
        return tensor, label


# ── Weighted Sampler ──────────────────────────────────────────────────────────

def make_weighted_sampler(labels: list[int]) -> WeightedRandomSampler:
    """
    Over-sample minority class to equalize expected class frequency per batch.
    Use this OR class-weighted loss — not both simultaneously.
    We use this (sampler) + ASL (which already handles imbalance internally).
    
    Using the sampler ensures every batch has balanced classes, which is more
    stable than loss weighting alone for heavily imbalanced datasets (>5:1).
    """
    label_counts = np.bincount(labels)
    # Weight per sample = 1 / count of its class
    weights = [1.0 / label_counts[l] for l in labels]
    return WeightedRandomSampler(
        weights     = torch.DoubleTensor(weights),
        num_samples = len(labels),
        replacement = True,
    )


# ── Discriminative LR Optimizer ───────────────────────────────────────────────

def build_optimizer(model: nn.Module, base_lr: float = 3e-4) -> torch.optim.Optimizer:
    """
    Discriminative learning rates — standard in production medical AI training.
    
    Rationale: early backbone layers encode low-level features (edges, textures)
    that transfer well; they should change slowly. The head must adapt fast.
    
    Layer group LR schedule (relative to base_lr):
        early layers (layer1, layer2) : base_lr × 0.01  (almost frozen)
        late layers  (layer3, layer4) : base_lr × 0.1   (fine-tune)
        classifier head  (fc)         : base_lr × 1.0   (train freely)
    """
    early, late, head = get_layer_groups(model)
    return torch.optim.AdamW(
        [
            {"params": early, "lr": base_lr * 0.01, "weight_decay": 1e-4},
            {"params": late,  "lr": base_lr * 0.1,  "weight_decay": 1e-4},
            {"params": head,  "lr": base_lr * 1.0,  "weight_decay": 1e-3},
        ],
        betas = (0.9, 0.999),
        eps   = 1e-8,
    )


# ── Metrics ───────────────────────────────────────────────────────────────────

class MedicalMetrics:
    """
    Tracks metrics appropriate for a medical classifier.
    Accuracy alone is misleading on imbalanced datasets.
    The primary metric for model selection is AUROC, not loss.
    """
    
    def __init__(self):
        self.reset()
    
    def reset(self):
        self.all_labels = []
        self.all_probs  = []
        self.all_preds  = []
    
    def update(self, logits: torch.Tensor, labels: torch.Tensor):
        probs = torch.softmax(logits, dim=1)[:, 1].detach().cpu().numpy()
        preds = (probs >= 0.5).astype(int)
        self.all_probs.extend(probs.tolist())
        self.all_preds.extend(preds.tolist())
        self.all_labels.extend(labels.cpu().numpy().tolist())
    
    def compute(self) -> dict:
        labels = np.array(self.all_labels)
        probs  = np.array(self.all_probs)
        preds  = np.array(self.all_preds)
        
        cm       = confusion_matrix(labels, preds)
        tn, fp, fn, tp = cm.ravel()
        
        sensitivity = tp / (tp + fn + 1e-8)   # recall — most critical: missed pneumonia
        specificity = tn / (tn + fp + 1e-8)   # true negative rate
        ppv         = tp / (tp + fp + 1e-8)   # precision
        npv         = tn / (tn + fn + 1e-8)   # negative predictive value
        
        try:
            auroc = roc_auc_score(labels, probs)
        except ValueError:
            auroc = 0.5  # single-class batch (shouldn't happen with WeightedSampler)
        
        return {
            "auroc":       auroc,
            "sensitivity": sensitivity,
            "specificity": specificity,
            "ppv":         ppv,
            "npv":         npv,
            "f1":          f1_score(labels, preds, zero_division=0),
        }


# ── Training Loop ─────────────────────────────────────────────────────────────

def train_epoch(
    model:      nn.Module,
    loader:     DataLoader,
    optimizer:  torch.optim.Optimizer,
    criterion:  nn.Module,
    device:     torch.device,
    scaler:     torch.cuda.amp.GradScaler,
    grad_clip:  float = 1.0,
) -> dict:
    model.train()
    metrics = MedicalMetrics()
    total_loss = 0.0
    
    for batch_idx, (images, labels) in enumerate(loader):
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)
        
        optimizer.zero_grad(set_to_none=True)
        
        # Mixed precision — cuts VRAM ~40%, speeds up ~1.5x on Ampere+
        with torch.cuda.amp.autocast(enabled=device.type == "cuda"):
            logits = model(images)
            loss   = criterion(logits, labels)
        
        scaler.scale(loss).backward()
        
        # Gradient clipping — essential for medical models where
        # single hard cases (e.g., very unusual opacity pattern) can
        # cause exploding gradients with ASL
        scaler.unscale_(optimizer)
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=grad_clip)
        
        scaler.step(optimizer)
        scaler.update()
        
        metrics.update(logits, labels)
        total_loss += loss.item()
    
    result = metrics.compute()
    result["loss"] = total_loss / len(loader)
    return result


@torch.no_grad()
def eval_epoch(
    model:     nn.Module,
    loader:    DataLoader,
    criterion: nn.Module,
    device:    torch.device,
) -> dict:
    model.eval()
    metrics = MedicalMetrics()
    total_loss = 0.0
    
    for images, labels in loader:
        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)
        
        with torch.cuda.amp.autocast(enabled=device.type == "cuda"):
            logits = model(images)
            loss   = criterion(logits, labels)
        
        metrics.update(logits, labels)
        total_loss += loss.item()
    
    result = metrics.compute()
    result["loss"] = total_loss / len(loader)
    return result


# ── Main ──────────────────────────────────────────────────────────────────────

def main(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info("Device: %s", device)
    
    # ── Load and split metadata ───────────────────────────────────────────────
    df = pd.read_csv(args.metadata_csv)
    df_train, df_val, df_test = build_stratified_splits(df)
    
    # ── Datasets and loaders ──────────────────────────────────────────────────
    train_aug = CXRAugmentation(is_training=True,  input_size=224)
    val_aug   = CXRAugmentation(is_training=False, input_size=224)
    
    mask_dir = Path(args.mask_dir)
    
    train_ds = MaskedCXRDataset(df_train, mask_dir, train_aug)
    val_ds   = MaskedCXRDataset(df_val,   mask_dir, val_aug)
    test_ds  = MaskedCXRDataset(df_test,  mask_dir, val_aug)
    
    train_sampler = make_weighted_sampler(df_train["label"].tolist())
    
    train_loader = DataLoader(
        train_ds,
        batch_size  = args.batch_size,
        sampler     = train_sampler,    # replaces shuffle=True
        num_workers = args.num_workers,
        pin_memory  = device.type == "cuda",
        persistent_workers = args.num_workers > 0,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size  = args.batch_size * 2,  # no grad → 2x batch for throughput
        shuffle     = False,
        num_workers = args.num_workers,
        pin_memory  = device.type == "cuda",
    )
    test_loader = DataLoader(
        test_ds,
        batch_size  = args.batch_size * 2,
        shuffle     = False,
        num_workers = args.num_workers,
    )
    
    # ── Model ─────────────────────────────────────────────────────────────────
    model = build_masked_cxr_resnet34(num_classes=2).to(device)
    
    # ── Loss ──────────────────────────────────────────────────────────────────
    criterion = AsymmetricLoss(gamma_pos=0.0, gamma_neg=4.0, clip=0.05)
    
    # ── Optimizer + Scheduler ─────────────────────────────────────────────────
    optimizer = build_optimizer(model, base_lr=args.lr)
    
    # OneCycleLR: reaches peak LR at 30% of training, then decays.
    # Outperforms step/cosine decay in medical imaging benchmarks (fastai research).
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr        = [args.lr * 0.01, args.lr * 0.1, args.lr],
        epochs        = args.epochs,
        steps_per_epoch = len(train_loader),
        pct_start     = 0.3,
        anneal_strategy = "cos",
        div_factor    = 25.0,     # initial_lr = max_lr / 25
        final_div_factor = 1e4,   # final_lr = max_lr / 10000
    )
    
    scaler = torch.cuda.amp.GradScaler(enabled=device.type == "cuda")
    
    # ── Training loop ─────────────────────────────────────────────────────────
    best_auroc   = 0.0
    patience_ctr = 0
    patience_max = 10  # early stopping
    
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    for epoch in range(1, args.epochs + 1):
        train_metrics = train_epoch(model, train_loader, optimizer, criterion,
                                    device, scaler)
        val_metrics   = eval_epoch(model,  val_loader,   criterion, device)
        scheduler.step()   # OneCycleLR steps per batch inside train_epoch;
                           # call once per epoch here if using epoch-level schedulers
        
        logger.info(
            "Epoch %3d/%d  "
            "train_loss=%.4f  train_auroc=%.4f  "
            "val_loss=%.4f  val_auroc=%.4f  "
            "val_sens=%.3f  val_spec=%.3f",
            epoch, args.epochs,
            train_metrics["loss"], train_metrics["auroc"],
            val_metrics["loss"],   val_metrics["auroc"],
            val_metrics["sensitivity"], val_metrics["specificity"],
        )
        
        # ── Model selection on AUROC (not loss) ───────────────────────────────
        if val_metrics["auroc"] > best_auroc:
            best_auroc   = val_metrics["auroc"]
            patience_ctr = 0
            torch.save(
                model.state_dict(),
                output_dir / "resnet34_pneumonia_masked_best.pth",
            )
            logger.info("  ✓ New best model saved (val_auroc=%.4f)", best_auroc)
        else:
            patience_ctr += 1
            if patience_ctr >= patience_max:
                logger.info("Early stopping at epoch %d (patience=%d)",
                            epoch, patience_max)
                break
    
    # ── Final test evaluation ─────────────────────────────────────────────────
    logger.info("Loading best model for final test evaluation …")
    model.load_state_dict(
        torch.load(output_dir / "resnet34_pneumonia_masked_best.pth",
                   map_location=device)
    )
    test_metrics = eval_epoch(model, test_loader, criterion, device)
    
    logger.info("="*60)
    logger.info("FINAL TEST METRICS:")
    for k, v in test_metrics.items():
        logger.info("  %-15s = %.4f", k, v)
    logger.info("="*60)
    
    # Save test metrics
    import json
    (output_dir / "test_metrics.json").write_text(
        json.dumps(test_metrics, indent=2)
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata-csv",  required=True,
                        help="CSV with image_path, patient_id, label, view, source")
    parser.add_argument("--mask-dir",      required=True,
                        help="Directory of pre-computed .npy lung masks")
    parser.add_argument("--output-dir",    default="./checkpoints")
    parser.add_argument("--epochs",        type=int,   default=50)
    parser.add_argument("--batch-size",    type=int,   default=32)
    parser.add_argument("--lr",            type=float, default=3e-4)
    parser.add_argument("--num-workers",   type=int,   default=4)
    args = parser.parse_args()
    main(args)